---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2017: true
parserOptions:
  ecmaVersion: 2018
plugins:
  - jest
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - prettier
rules:
  strict: [error]
